---
## Nomad Package
nomad_version: 1.3.2

### Nomad settings
nomad_datacenter: "aperture"
nomad_region: "redbrick"
nomad_log_level: "INFO"
nomad_syslog_enable: true
nomad_iface: "{{ ansible_default_ipv4.interface }}"
nomad_node_name: "{{ inventory_hostname_short }}"
nomad_node_role: "both"

#### Server settings
nomad_retry_max: 3
nomad_retry_join: true
nomad_retry_interval: "30s"
nomad_rejoin_after_leave: false

### Servers
nomad_group_name: "nomad"
