---
github_users:
  - user: distro
    account: DistroByte
    groups: [sudo, docker]

github_url: https://github.com

apt_packages:
  - cron
  - curl
  - git
  - htop
  - net-tools
  - nmap
  - sysstat
  - vim
