---
- name: apt update packages to their latest version and autoclean
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoclean: yes
  when: ansible_os_family == "Debian" and apt_update_packages

- name: install common tools
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ apt_packages }}"
  when: ansible_os_family == "Debian" and apt_install_packages
