- name: Installing Nomad
  hosts: nomad
  become: yes
  roles:
    - { role: ansible-community.nomad }

  vars_files:
    - ../group_vars/vars.yml

  tasks:
    - name: Start nomad
      service: name=nomad state=started enabled=yes