---
- name: Install fail2ban from apt
  ansible.builtin.apt:
    name: fail2ban
    state: latest

- name: Copy configuraion to host
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    force: no

- name: Restart fail2ban to apply config
  ansible.builtin.service:
    name: fail2ban
    state: restarted
