---
- name: "Create {{ user_pihole }} system user and group (nologin shell)"
  ansible.builtin.user:
    name: "{{ user_pihole }}"
    state: present
    system: yes
    shell: /usr/sbin/nologin

- name: Create Pi-Hole configuration directory
  ansible.builtin.file:
    name: "{{ fspath_pihole_config }}"
    state: directory
    owner: "{{ user_pihole }}"
    group: "{{ user_pihole }}"
    mode: 0755

- name: Prepare Pi-Hole configuration
  ansible.builtin.template:
    src: "setupVars.conf.j2"
    dest: "{{ fspath_pihole_config }}/setupVars.conf"
    owner: root
    group: root
    mode: 0644
