---
- name: Install OS packages
  ansible.builtin.include_tasks: install.yml

- name: Create directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  with_items:
    - "{{ nomad_data_dir }}"
    - "{{ nomad_plugin_dir }}"

- name: Create config directory
  ansible.builtin.file:
    dest: "{{ nomad_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755