---
- name: Update apt cache (Debian)
  apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"

- name: Ensure git is installed (Debian)
  apt:
    pkg:
      - git
  when: ansible_os_family == "Debian"
